import { Component } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

export interface Pais {
  id: string; // Alfanumérico
  nombre: string;
}

@Component({
  selector: 'app-paises',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './paises.html',
  styleUrl: './paises.scss'
})
export class Paises {
  constructor(private router: Router, private route: ActivatedRoute) { }

  closeModal() {
    this.router.navigate(['../'], { relativeTo: this.route });
  }

  paisesBD: Pais[] = [
    { id: '301', nombre: 'AFGANISTAN' },
    { id: '401', nombre: 'ALBANIA' },
    { id: '402', nombre: 'ALEMANIA FEDERAL' },
    { id: '403', nombre: 'ALEMANIA ORIENTAL' },
    { id: '430', nombre: 'ALEMANIA,REP.FED.' },
    { id: '404', nombre: 'ANDORRA' },
    { id: '143', nombre: 'ANGOLA' },
    { id: '652', nombre: 'ANGUILA (TERRITORIO NO AUTONOMO DEL R. UNIDO)' },
    { id: '237', nombre: 'ANTIGUA Y BARBUDA' },
    { id: '241', nombre: 'ANTILLAS HOLANDESAS' },
    { id: '653', nombre: 'ANTILLAS HOLANDESAS (TERRITORIO DE PAISES BAJOS)' },
    { id: '302', nombre: 'ARABIA SAUDITA' },
    { id: '636', nombre: 'ARCHIPIELAGO DE SVALBARD' },
    { id: '102', nombre: 'ARGELIA' },
    { id: '200', nombre: 'ARGENTINA' },
    { id: '343', nombre: 'ARMENIA' },
    { id: '242', nombre: 'ARUBA' },
    { id: '659', nombre: 'ARUBA (TERRITORIO DE PAISES BAJOS)' },
    { id: '662', nombre: 'ASCENCION' },
    { id: '501', nombre: 'AUSTRALIA' },
    { id: '405', nombre: 'AUSTRIA' },
    { id: '358', nombre: 'AZERBAIJAN' },
    { id: '230', nombre: 'BAHAMAS' },
    { id: '303', nombre: 'BAHREIN' },
    { id: '345', nombre: 'BANGLADESH' },
    { id: '201', nombre: 'BARBADOS' },
    { id: '406', nombre: 'BELGICA' },
    { id: '236', nombre: 'BELICE' },
    { id: '112', nombre: 'BENIN' },
    { id: '663', nombre: 'BERMUDAS (TERRITORIO NO AUTONOMO DEL R UNIDO)' },
    { id: '435', nombre: 'BIELORRUSIA' },
    { id: '202', nombre: 'BOLIVIA' },
    { id: '446', nombre: 'BOSNIA HERZEGOVINA' },
    { id: '103', nombre: 'BOTSWANA' },
    { id: '203', nombre: 'BRASIL' },
    { id: '346', nombre: 'BRUNEI' },
    { id: '407', nombre: 'BULGARIA' },
    { id: '101', nombre: 'BURKINA FASO' },
    { id: '104', nombre: 'BURUNDI' },
    { id: '305', nombre: 'BUTAN' },
    { id: '150', nombre: 'CABO VERDE' },
    { id: '306', nombre: 'CAMBODYA(EX-KAMPUCHEA)' },
    { id: '105', nombre: 'CAMERUN' },
    { id: '664', nombre: 'CAMPIONE D\'ITALIA' },
    { id: '204', nombre: 'CANADA' },
    { id: '111', nombre: 'CHAD' },
    { id: '408', nombre: 'CHECOSLOVAQUIA' },
    { id: '208', nombre: 'CHILE' },
    { id: '310', nombre: 'CHINA' },
    { id: '311', nombre: 'CHIPRE' },
    { id: '455', nombre: 'CHIPRE' },
    { id: '206', nombre: 'COLOMBIA' },
    { id: '665', nombre: 'COLONIA DE GIBRALTAR' },
    { id: '155', nombre: 'COMORAS' },
    { id: '108', nombre: 'CONGO' },
    { id: '308', nombre: 'COREA DEMOCRATICA' },
    { id: '309', nombre: 'COREA REPUBLICANA' },
    { id: '110', nombre: 'COSTA DE MARFIL' },
    { id: '209', nombre: 'COSTA RICA' },
    { id: '447', nombre: 'CROACIA' },
    { id: '207', nombre: 'CUBA' },
    { id: '409', nombre: 'DINAMARCA' },
    { id: '159', nombre: 'DJIBOUTI' },
    { id: '239', nombre: 'DOMINICA' },
    { id: '205', nombre: 'DOMINICANA,REP.' },
    { id: '210', nombre: 'ECUADOR' },
    { id: '113', nombre: 'EGIPTO' },
    { id: '211', nombre: 'EL SALVADOR' },
    { id: '331', nombre: 'EMIRATOS ARABES,UNID' },
    { id: '160', nombre: 'ERITREA' },
    { id: '448', nombre: 'ESLOVAQUIA' },
    { id: '445', nombre: 'ESLOVENIA' },
    { id: '410', nombre: 'ESPAÑA' },
    { id: '212', nombre: 'ESTADOS UNIDOS' },
    { id: '440', nombre: 'ESTONIA' },
    { id: '161', nombre: 'ETIOPIA' },
    { id: '452', nombre: 'FED. SER Y MONT YUGOE' },
    { id: '512', nombre: 'FIJI, ISLAS' },
    { id: '312', nombre: 'FILIPINAS' },
    { id: '411', nombre: 'FINLANDIA' },
    { id: '412', nombre: 'FRANCIA' },
    { id: '115', nombre: 'GABON' },
    { id: '116', nombre: 'GAMBIA' },
    { id: '314', nombre: 'GAZA' },
    { id: '351', nombre: 'GEORGIA' },
    { id: '117', nombre: 'GHANA' },
    { id: '240', nombre: 'GRANADA' },
    { id: '413', nombre: 'GRECIA' },
    { id: '666', nombre: 'GROENLANDIA' },
    { id: '667', nombre: 'GUAM (TERRITORIO NO AUTONOMO DE LOS ESTADO UNIDOS' },
    { id: '213', nombre: 'GUATEMALA' },
    { id: '118', nombre: 'GUINEA' },
    { id: '156', nombre: 'GUINEA BISSAU' },
    { id: '119', nombre: 'GUINEA ECUATORIAL' },
    { id: '214', nombre: 'GUYANA' },
    { id: '215', nombre: 'HAITI' },
    { id: '414', nombre: 'HOLANDA' },
    { id: '216', nombre: 'HONDURAS' },
    { id: '341', nombre: 'HONG KONG' },
    { id: '660', nombre: 'HONG KONG (TERRITORIO DE CHINA)' },
    { id: '415', nombre: 'HUNGRIA' },
    { id: '990', nombre: 'INDET.(ASIA)' },
    { id: '991', nombre: 'INDET.(CONTINENTE)' },
    { id: '490', nombre: 'INDET.(EUROPA)' },
    { id: '590', nombre: 'INDET.(OCEANIA)' },
    { id: '190', nombre: 'INDETERMINADO (AFRICA)' },
    { id: '290', nombre: 'INDETERMINADO.(AMERICA)' },
    { id: '315', nombre: 'INDIA' },
    { id: '316', nombre: 'INDONESIA' },
    { id: '317', nombre: 'IRAK' },
    { id: '318', nombre: 'IRAN' },
    { id: '416', nombre: 'IRLANDA' },
    { id: '670', nombre: 'ISLAS TURKAS Y CAICOS (TERRITORIO NO AUTONOMO DEL REINO UNIDO)' },
    { id: '672', nombre: 'ISLA CHRISTMAS' },
    { id: '673', nombre: 'ISLA DE COCOS O KEELING' },
    { id: '674', nombre: 'ISLA DE COOK (TERRITORIO AUTONOMO ASOCIADO A NUEVA ZELANDA)' },
    { id: '676', nombre: 'ISLA DE MAN (TERRITORIO DEL REINO UNIDO)' },
    { id: '677', nombre: 'ISLA DE NORFOLK (TERRITORIO DEL R UNIDO)' },
    { id: '681', nombre: 'ISLA QESHM' },
    { id: '417', nombre: 'ISLANDIA' },
    { id: '669', nombre: 'ISLAS AZORES' },
    { id: '671', nombre: 'ISLAS CAIMAN (TERRITORIO NO AUTONOMO DE R UNIDO)' },
    { id: '680', nombre: 'ISLAS DE SAN PEDRO Y MIQUELON' },
    { id: '678', nombre: 'ISLAS DEL CANAL (GUERNESEY, JERSEY, ALDERNEY,G.STARK, L.SARK, ETC)' },
    { id: '254', nombre: 'ISLAS MALVINAS' },
    { id: '679', nombre: 'ISLAS PACIFICO' },
    { id: '682', nombre: 'ISLAS VIRGENES BRITANICAS (TERRITORIO NO AUTONOMO DEL REINO UNIDO)' },
    { id: '683', nombre: 'ISLAS VIRGENES DE ESTADOS UNIDOS DE AMERICA' },
    { id: '319', nombre: 'ISRAEL' },
    { id: '418', nombre: 'ITALIA' },
    { id: '217', nombre: 'JAMAICA' },
    { id: '320', nombre: 'JAPON' },
    { id: '321', nombre: 'JORDANIA' },
    { id: '352', nombre: 'KAZAJSTAN' },
    { id: '120', nombre: 'KENYA' },
    { id: '353', nombre: 'KIRGUIZISTAN' },
    { id: '514', nombre: 'KIRIBATI, ISLAS' },
    { id: '323', nombre: 'KUWAIT' },
    { id: '684', nombre: 'LABUAN' },
    { id: '324', nombre: 'LAOS' },
    { id: '121', nombre: 'LESOTHO' },
    { id: '441', nombre: 'LETONIA' },
    { id: '325', nombre: 'LIBANO' },
    { id: '122', nombre: 'LIBERIA' },
    { id: '123', nombre: 'LIBIA' },
    { id: '419', nombre: 'LIECHTENSTEIN' },
    { id: '442', nombre: 'LITUANIA' },
    { id: '420', nombre: 'LUXEMBURGO' },
    { id: '344', nombre: 'MACAO' },
    { id: '450', nombre: 'MACEDONIA' },
    { id: '124', nombre: 'MADAGASCAR' },
    { id: '685', nombre: 'MADEIRA (TERRITORIO DE PORTUGAL)' },
    { id: '326', nombre: 'MALASIA' },
    { id: '125', nombre: 'MALAWI' },
    { id: '327', nombre: 'MALDIVAS ISLAS' },
    { id: '126', nombre: 'MALI' },
    { id: '255', nombre: 'MAR ARG ZONA ECO.EX' },
    { id: '521', nombre: 'MARIANAS,ISLAS' },
    { id: '127', nombre: 'MARRUECOS' },
    { id: '520', nombre: 'MARSHALL,ISLAS' },
    { id: '128', nombre: 'MAURICIO,ISLAS' },
    { id: '129', nombre: 'MAURITANIA' },
    { id: '218', nombre: 'MEXICO' },
    { id: '515', nombre: 'MICRONESIA,EST.FEDER' },
    { id: '449', nombre: 'MOLDAVIA' },
    { id: '421', nombre: 'MONACO' },
    { id: '686', nombre: 'MONSERRAT (TERRITORIO NO AUTONOMO DEL REINO UNIDO)' },
    { id: '453', nombre: 'MONTENEGRO' },
    { id: '151', nombre: 'MOZAMBIQUE' },
    { id: '304', nombre: 'MYANMAR (EX-BIRMANIA)' },
    { id: '158', nombre: 'NAMIBIA' },
    { id: '509', nombre: 'NAURU' },
    { id: '330', nombre: 'NEPAL' },
    { id: '219', nombre: 'NICARAGUA' },
    { id: '130', nombre: 'NIGER' },
    { id: '131', nombre: 'NIGERIA' },
    { id: '687', nombre: 'NIUE' },
    { id: '422', nombre: 'NORUEGA' },
    { id: '504', nombre: 'NUEVA ZELANDIA' },
    { id: '328', nombre: 'OMAN' },
    { id: '999', nombre: 'OTROS PAISES' },
    { id: '423', nombre: 'PAISES BAJOS' },
    { id: '332', nombre: 'PAKISTAN' },
    { id: '516', nombre: 'PALAU' },
    { id: '220', nombre: 'PANAMA' },
    { id: '519', nombre: 'PAPUA NUEVA GUINEA' },
    { id: '221', nombre: 'PARAGUAY' },
    { id: '655', nombre: 'PATAU' },
    { id: '222', nombre: 'PERU' },
    { id: '630', nombre: 'PITCAIRN' },
    { id: '656', nombre: 'POLINESIA FRANCESA (TERRITORIO DE ULTRAMAR DE FRANCIA)' },
    { id: '424', nombre: 'POLONIA' },
    { id: '425', nombre: 'PORTUGAL' },
    { id: '499', nombre: 'POS.BRIT.(EUROPA)' },
    { id: '223', nombre: 'PUERTO RICO' },
    { id: '322', nombre: 'QATAR' },
    { id: '699', nombre: 'REGIMEN APLICABLE A LAS SA FINANCIERAS (LEY 11079 DE LA ROU)' },
    { id: '426', nombre: 'REINO UNIDO' },
    { id: '107', nombre: 'REP.CENTROAFRICANA.' },
    { id: '451', nombre: 'REP.CHECA' },
    { id: '109', nombre: 'REP.DEMOCRAT.DEL CONGO EX ZAIRE' },
    { id: '148', nombre: 'REPUBLICA DE SUDAFRICA' },
    { id: '348', nombre: 'REPUBLICA DE YEMEN' },
    { id: '197', nombre: 'RESTO (AFRICA)' },
    { id: '297', nombre: 'RESTO AMERICA' },
    { id: '997', nombre: 'RESTO CONTINENTE' },
    { id: '397', nombre: 'RESTO DE ASIA' },
    { id: '497', nombre: 'RESTO EUROPA' },
    { id: '597', nombre: 'RESTO OCEANIA' },
    { id: '256', nombre: 'RIOS ARG NAVEG INTER' },
    { id: '427', nombre: 'RUMANIA' },
    { id: '444', nombre: 'RUSIA' },
    { id: '133', nombre: 'RWANDA' },
    { id: '238', nombre: 'S.CRISTOBAL Y NEVIS' },
    { id: '518', nombre: 'SALOMON,ISLAS' },
    { id: '693', nombre: 'SAMOA AMERICANA (TERRITORIO NO AUTONOMO DE LOS ESTADOS UNIDOS)' },
    { id: '506', nombre: 'SAMOA OCCIDENTAL' },
    { id: '428', nombre: 'SAN MARINO' },
    { id: '235', nombre: 'SAN VICENTE Y LAS GRANADINAS' },
    { id: '694', nombre: 'SANTA ELENA' },
    { id: '234', nombre: 'SANTA LUCIA' },
    { id: '265', nombre: 'SECTOR ANTARTICO ARG.' },
    { id: '134', nombre: 'SENEGAL' },
    { id: '454', nombre: 'SERBIA' },
    { id: '132', nombre: 'SEYCHELLES' },
    { id: '135', nombre: 'SIERRA LEONA' },
    { id: '333', nombre: 'SINGAPUR' },
    { id: '334', nombre: 'SIRIA' },
    { id: '136', nombre: 'SOMALIA' },
    { id: '307', nombre: 'SRILANKA' },
    { id: '157', nombre: 'STO.TOME Y PRINCIPE' },
    { id: '153', nombre: 'SUDAFRICA' },
    { id: '138', nombre: 'SUDAN' },
    { id: '429', nombre: 'SUECIA' },
    { id: '232', nombre: 'SURINAME' },
    { id: '137', nombre: 'SWAZILANDIA' },
    { id: '139', nombre: 'TANZANIA' },
    { id: '354', nombre: 'TAYIKISTAN' },
    { id: '510', nombre: 'TER.VINCULADOS A NUEVA. ZELANDA' },
    { id: '511', nombre: 'TER. VINCULADOS A ESTADOS UNIDOS' },
    { id: '228', nombre: 'TER.VINCULADOS A DINAMARCA' },
    { id: '231', nombre: 'TER.VINCULADOS A ESTADOS UNIDOS' },
    { id: '357', nombre: 'TERR. AU. PALESTINOS' },
    { id: '227', nombre: 'TERRIT.VINCULADO AL R.UNIDO' },
    { id: '146', nombre: 'TERRIT.VINCULADOS A ESPAÑA' },
    { id: '147', nombre: 'TERRIT.VINCULADOS A FRANCIA' },
    { id: '229', nombre: 'TERRIT.VINCULADOS A FRANCIA AMERIC.' },
    { id: '140', nombre: 'TERRIT.VINCULADOS A PORTUGAL' },
    { id: '145', nombre: 'TERRIT.VINCULADOS AL R UNIDO' },
    { id: '507', nombre: 'TERRITORIOS VINCULADOS A AUSTRALIA' },
    { id: '508', nombre: 'TERRITORIOS VINCULADOS AL R. UNIDO' },
    { id: '335', nombre: 'THAILANDIA' },
    { id: '250', nombre: 'TIERRA DEL FUEGO' },
    { id: '350', nombre: 'TIMOR ORIENTAL' },
    { id: '638', nombre: 'TRIESTE (ITALIA)' },
    { id: '224', nombre: 'TRINIDAD Y -TOBAGO' },
    { id: '697', nombre: 'TRISTAN DACUNHA' },
    { id: '141', nombre: 'TUNEZ' },
    { id: '355', nombre: 'TURKMENISTAN' },
    { id: '336', nombre: 'TURQUIA' },
    { id: '436', nombre: 'TURQUIA' },
    { id: '517', nombre: 'TUVALU' },
    { id: '142', nombre: 'UGANDA' },
    { id: '601', nombre: 'URSS' },
    { id: '225', nombre: 'URUGUAY' },
    { id: '356', nombre: 'UZBEKISTAN' },
    { id: '505', nombre: 'VANUATU' },
    { id: '431', nombre: 'VATICANO (SANTA SEDE)' },
    { id: '226', nombre: 'VENEZUELA' },
    { id: '337', nombre: 'VIETNAM' },
    { id: '432', nombre: 'YUGOSLAVIA' },
    { id: '144', nombre: 'ZAMBIA' }
  ];

  searchTerm: string = '';

  get paisesFiltrados(): Pais[] {
    return this.paisesBD.filter(p =>
      p.nombre.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
      p.id.toLowerCase().includes(this.searchTerm.toLowerCase())
    );
  }
}
